### ISSUE TITLE
accelerate process to remove duplicate article

### ISSUE THREAD

**Issue by andrea-w-wang** [disinfoRG/ZeroScraper#91]
The current workflow is slow:

`duplicates = [{'url': 'https://udn.com/news/story/7323/4263400', 'count': 7},{'url': 'https://udn.com/news/story/7320/4252581', 'count': 6},....]`

```python
for dup in duplicates:
    ids = [x['article_id'] for x in queries.get_multiple_id_by_url(url=dup['url'], limit=dup['count']-1)]
    for id in ids:
        queries.delete_article(article_id=id)
        queries.delete_snapshot(article_id=id) 
```

[get_multiple_id_by_url](https://github.com/disinfoRG/ZeroScraper/blob/master/queries/get_multiple_id_by_url.sql)
[delete_article](https://github.com/disinfoRG/ZeroScraper/blob/master/queries/delete_article.sql)
[delete_snapshot](https://github.com/disinfoRG/ZeroScraper/blob/master/queries/delete_snapshot.sql)

**Comment by pm5** [comment]
@andrea-w-wang try to use `url_hash` in `get_multiple_id_by_url` as we did in `get_article_id_by_url`.  Should be much much faster.

**Comment by andrea-w-wang** [comment]
@pm5, yes it's much faster now!

commit 809cecacd2a0ecbe2e734763fa928363b08471a7 -- use url_hash instead of url to to find duplicate url

**Comment by pm5** [comment]
@andrea-w-wang you still need to check `url` in the SQL in the rare cases where CRC32 has a collision, so:

```sql
SELECT article_id
FROM Article
WHERE url_hash = :url_hash AND url = :url
order by snapshot_count asc
limit :limit;
```

**Comment by andrea-w-wang** [comment]
I have checked that the duplicates I’m looking at right now have no CRC32
collision, but will change the sql accordingly for future usage.


On Mon, Mar 23, 2020 at 22:28 Pomin Wu <notifications@github.com> wrote:

> @andrea-w-wang
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_andrea-2Dw-2Dwang&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=wieynlWpSInfvirzhMI7vQ&m=uAbcM2DDcy_30071X0_tCbrgifZ1kzbEU9Sy_tEJmNI&s=CABDzxP8J_3fKfHNjMOkjUS_EvSIPUN3t5diORbY-Cc&e=>
> you still need to check url in the SQL in the rare cases where CRC32 has
> a collision, so:
>
> SELECT article_idFROM ArticleWHERE url_hash = :url_hash AND url = :urlorder by snapshot_count asclimit :limit;
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_disinfoRG_ZeroScraper_issues_91-23issuecomment-2D602973164&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=wieynlWpSInfvirzhMI7vQ&m=uAbcM2DDcy_30071X0_tCbrgifZ1kzbEU9Sy_tEJmNI&s=3_EGKTx3Q8zw2Ex0O-yfdvJf1xDnAcN6PeT0kzi6QQw&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AHWPRTQ4IDDIGDGNS7K7B73RJALGLANCNFSM4LR3TLDQ&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=wieynlWpSInfvirzhMI7vQ&m=uAbcM2DDcy_30071X0_tCbrgifZ1kzbEU9Sy_tEJmNI&s=-onDSkVD8qKD-J8Y3n2EoKKEEm1aFR-WZKdS7pnLMEE&e=>
> .
>
-- 
Andrea Wang
Master of Science in Data Science, 2019
LinkedIn <https://www.linkedin.com/in/andrea-w-wang-216710119/> | Github
<https://github.com/andrea-w-wang/>

**Comment by pm5** [comment]
MySQL query optimizers would try to guess the fastest way to run a query, in particular which possible indexes can be used to speed things up (you can see this with `EXPLAIN`).  In this case it would find out that there is an `ik_Article_url_hash` index with which it can (substantially) narrow down the range of search without doing a full table scan.  There are likely very few hash collisions, so in most cases a table scan is not needed at all after using the index.  Without the clause it would have to do a full table scan every time, which is much slower for big tables.

What we would really like to have here is perhaps an index on `url` field itself.  But `VARCHAR` is not a good data type to create indexes from --- it's fairly big in its size, resulting in big indexes.  Besides, MySQL has a limit on `VARCHAR` column length if you want to index it, something around 64 I think.  To work with `VARCHAR` we could have created an index out of the first n characters of these string values, but since URLs from the same domain differ only on those parts on the right, this scheme does not work well here.  That is why we use a `url_hash` column which is more index-able.
